version: "databricks-clay.readthedocs.io/en/alpha1/"
name: jaffle_shop
description: "Data feed for {{project}} operations. An operational feed may consist of one or more layers and data sources."
layers:
  - name: landing
    description: "where data is landed in file format as a pure replica of the source datastore data object"
    datastores:
      - name: "{{project}}"
        description: "{{datastore}} {{project}} source operational database"
        # note the type here
        type: adls
        data_dir: data
      - name: stripe
        description: "{{project}} source operational sales transactions"
        # note that it's repeated again here
        type: adls
        data_dir: data

  - name: raw
    description: "data is shredded if necessary with some basic cleansing and validation"
    # note the top down inheritance, in landing we defined the type in each datastore
    # this is useful if they're different, but annoying if not
    # whereas here we define it at the layer level and it cascades down unless overriden in a datastore
    type: deltalake
    datastores:
      - name: "{{layer}}_{{project}}"
        description: "{{project}} source operational database"
      - name: "{{layer}}_stripe"
        description: "{{project}} source operational sales transactions"

  - name: prepared
    description: "data is modelled into an operational analytics store"
    type: deltalake
    datastores:
      - name: "{{layer}}_{{project}}"
        description: "{{layer}} operational {{project}}"

  - name: dw
    description: "data is modelled into a data warehouse"
    type: deltalake
    datastores:
      - name: "{{layer}}_{{project}}"
        description: "jaffle shop data {{layer}}"
